-- MySQL 버전
CREATE DATABASE WEATHER DEFAULT CHARSET=utf8 collate=utf8_bin;

USE WEATHER;

-- USER
CREATE TABLE USERLIST(
    User_id VARCHAR(15) UNIQUE NOT NULL,
    PW VARCHAR(256) NOT NULL,
    Uniq_id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Nickname VARCHAR(15) NOT NULL,
    Fvweather VARCHAR(50),
    Available VARCHAR(1) DEFAULT 'Y' NOT NULL
);

-- REGION
CREATE TABLE REGION(
    Uuid BIGINT NOT NULL,
    Address VARCHAR(50) NOT NULL,
    Latitude DECIMAL(18,14) NOT NULL,
    Longitude DECIMAL(18,14) NOT NULL,
    X_coor INT NOT NULL,
    Y_coor INT NOT NULL,
    PRIMARY KEY(Uuid, Address)
);
ALTER TABLE REGION ADD FOREIGN KEY(Uuid) REFERENCES USERLIST(Uniq_id) ON DELETE CASCADE;

-- WTYPE
CREATE TABLE WTYPE(
    Wcode VARCHAR(10) NOT NULL,
    Message VARCHAR(30) NOT NULL,
    Wname VARCHAR(20) NOT NULL,
    PRIMARY KEY(Wcode)
);

-- WEATEHR_RECORD
CREATE TABLE WEATHER_RECORD(
    Uuid BIGINT NOT NULL,
    Rdate DATE NOT NULL,
    Address VARCHAR(50),
    Wcode VARCHAR(10),
    Temp DECIMAL(3,1),
    Tfeel VARCHAR(30),
    Humidity  INT,
    Hfeel VARCHAR(30),
    Precipitation DECIMAL(5,1),
    Pfeel VARCHAR(30),
    PRIMARY KEY(Uuid,Rdate)
);
ALTER TABLE WEATHER_RECORD ADD FOREIGN KEY(Uuid) REFERENCES USERLIST(Uniq_id) ON DELETE CASCADE;
ALTER TABLE WEATHER_RECORD ADD FOREIGN KEY(Wcode) REFERENCES WTYPE(Wcode);

COMMIT;
